/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
import javax.swing.*;
import java.time.*;
import java.time.format.TextStyle;
import java.util.*;
import java.time.temporal.ChronoUnit;
public class PenghitungHariFrame extends javax.swing.JFrame {

    /**
     * Creates new form PenghitungHariFrame
     */
    public PenghitungHariFrame() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(52, 73, 94));
        txtHasil.setEditable(false);
        ((JSpinner.NumberEditor) spnTahun.getEditor()).getFormat().applyPattern("####");

        // Inisialisasi awal
        Calendar cal = Calendar.getInstance();
        spnTahun.setValue(cal.get(Calendar.YEAR));
        cmbBulan.setSelectedIndex(0);
        kalender1.setCalendar(cal);
        kalender2.setCalendar(cal);

        // --- Event Listeners ---
        cmbBulan.addActionListener(e -> updateKalenderDariCombo());
        spnTahun.addChangeListener(e -> updateKalenderDariCombo());
        kalender1.addPropertyChangeListener("calendar", e -> updateComboDariKalender());

        btnHitung.addActionListener(e -> hitungHari());
        btnSelisih.addActionListener(e -> hitungSelisih());
        btnHapus.addActionListener(e -> hapusData());
        btnKeluar.addActionListener(e -> keluarAplikasi());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHitungHari = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblBulan = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        cmbBulan = new javax.swing.JComboBox<>();
        spnTahun = new javax.swing.JSpinner();
        lblHari = new javax.swing.JLabel();
        scrlHasil = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();
        kalender2 = new com.toedter.calendar.JCalendar();
        btnHitung = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        kalender1 = new com.toedter.calendar.JCalendar();
        btnSelisih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHitungHari.setBackground(new java.awt.Color(52, 73, 94));
        panelHitungHari.setForeground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("APLIKASI PENGHITUNG HARI");

        lblBulan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBulan.setForeground(new java.awt.Color(255, 255, 255));
        lblBulan.setText("PILIH BULAN:");

        lblTahun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTahun.setForeground(new java.awt.Color(255, 255, 255));
        lblTahun.setText("PILIH TAHUN:");

        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        lblHari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHari.setForeground(new java.awt.Color(255, 255, 255));
        lblHari.setText("HASIL PERHITUNGAN:");

        txtHasil.setColumns(20);
        txtHasil.setRows(5);
        scrlHasil.setViewportView(txtHasil);

        btnHitung.setBackground(new java.awt.Color(0, 204, 0));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("HITUNG");

        btnHapus.setBackground(new java.awt.Color(255, 255, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("HAPUS");

        btnKeluar.setBackground(new java.awt.Color(204, 0, 0));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("KELUAR");

        btnSelisih.setBackground(new java.awt.Color(0, 102, 255));
        btnSelisih.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelisih.setForeground(new java.awt.Color(255, 255, 255));
        btnSelisih.setText("HITUNG SELISIH");

        javax.swing.GroupLayout panelHitungHariLayout = new javax.swing.GroupLayout(panelHitungHari);
        panelHitungHari.setLayout(panelHitungHariLayout);
        panelHitungHariLayout.setHorizontalGroup(
            panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHitungHariLayout.createSequentialGroup()
                .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHitungHariLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHitungHariLayout.createSequentialGroup()
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelHitungHariLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelHitungHariLayout.createSequentialGroup()
                                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSelisih))
                                    .addComponent(lblHari)))
                            .addGroup(panelHitungHariLayout.createSequentialGroup()
                                .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelHitungHariLayout.createSequentialGroup()
                                        .addComponent(lblBulan)
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHitungHariLayout.createSequentialGroup()
                                        .addComponent(lblTahun)
                                        .addGap(18, 18, 18)))
                                .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbBulan, javax.swing.GroupLayout.Alignment.TRAILING, 0, 196, Short.MAX_VALUE)
                                    .addComponent(spnTahun, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kalender2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kalender1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelHitungHariLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lblJudul)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelHitungHariLayout.setVerticalGroup(
            panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHitungHariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHitungHariLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBulan)
                            .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTahun)
                            .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHitung)
                            .addComponent(btnSelisih))
                        .addGap(18, 18, 18)
                        .addComponent(lblHari)
                        .addGap(18, 18, 18))
                    .addGroup(panelHitungHariLayout.createSequentialGroup()
                        .addComponent(kalender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHitungHariLayout.createSequentialGroup()
                        .addComponent(scrlHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelHitungHariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus)
                            .addComponent(btnKeluar)))
                    .addComponent(kalender2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelHitungHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelHitungHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void updateKalenderDariCombo() {
    int bulan = cmbBulan.getSelectedIndex();
    if (bulan <= 0) return;
    int tahun = (int) spnTahun.getValue();
    Calendar cal = Calendar.getInstance();
    cal.set(tahun, bulan - 1, kalender1.getCalendar().get(Calendar.DAY_OF_MONTH));
    kalender1.setCalendar(cal);
}

    private void updateComboDariKalender() {
        Calendar cal = kalender1.getCalendar();
        cmbBulan.setSelectedIndex(cal.get(Calendar.MONTH) + 1);
        spnTahun.setValue(cal.get(Calendar.YEAR));
    }

    // --- Fungsi utama ---
    private void hitungHari() {
        int bulan = cmbBulan.getSelectedIndex();
        if (bulan <= 0) {
            JOptionPane.showMessageDialog(this, "Pilih bulan terlebih dahulu!");
            return;
        }
        int tahun = (int) spnTahun.getValue();
        YearMonth ym = YearMonth.of(tahun, bulan);
        int jmlHari = ym.lengthOfMonth();
        LocalDate awal = LocalDate.of(tahun, bulan, 1);
        LocalDate akhir = LocalDate.of(tahun, bulan, jmlHari);

        String hariAwal = awal.getDayOfWeek().getDisplayName(TextStyle.FULL, new Locale("id", "ID"));
        String hariAkhir = akhir.getDayOfWeek().getDisplayName(TextStyle.FULL, new Locale("id", "ID"));
        String infoKabisat = Year.isLeap(tahun) ? "(Tahun Kabisat)" : "(Bukan Tahun Kabisat)";

        txtHasil.setText(
            "Bulan: " + cmbBulan.getSelectedItem() + " " + tahun + " " + infoKabisat + "\n" +
            "Jumlah Hari: " + jmlHari + "\n" +
            "Hari Pertama: " + hariAwal + "\n" +
            "Hari Terakhir: " + hariAkhir
        );
    }

    private void hitungSelisih() {
        Date tgl1 = kalender1.getDate();
        Date tgl2 = kalender2.getDate();
        if (tgl1 == null || tgl2 == null) {
            JOptionPane.showMessageDialog(this, "Pilih dua tanggal terlebih dahulu!");
            return;
        }

        // Konversi Date ke LocalDate agar mudah diformat
        LocalDate tanggal1 = tgl1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate tanggal2 = tgl2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Hitung selisih hari absolut
        long selisihHari = Math.abs(ChronoUnit.DAYS.between(tanggal1, tanggal2));

        // Format tanggal ke gaya Indonesia
        java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", new Locale("id", "ID"));

        // Tampilkan hasil lebih informatif
        txtHasil.setText(
            "Tanggal pertama: " + tanggal1.format(fmt) + "\n" +
            "Tanggal kedua:   " + tanggal2.format(fmt) + "\n" +
            "Selisih antara dua tanggal: " + selisihHari + " hari"
        );
    }

    private void hapusData() {
        int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin menghapus data?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            cmbBulan.setSelectedIndex(0);
            spnTahun.setValue(2025);
            Calendar now = Calendar.getInstance();
            kalender1.setCalendar(now);
            kalender2.setCalendar(now);
            txtHasil.setText("");
            cmbBulan.setSelectedIndex(0);
            
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void keluarAplikasi() {
        if (JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan aplikasi!");
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungHariFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSelisih;
    private javax.swing.JComboBox<String> cmbBulan;
    private com.toedter.calendar.JCalendar kalender1;
    private com.toedter.calendar.JCalendar kalender2;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JPanel panelHitungHari;
    private javax.swing.JScrollPane scrlHasil;
    private javax.swing.JSpinner spnTahun;
    private javax.swing.JTextArea txtHasil;
    // End of variables declaration//GEN-END:variables
}
